config/routes.rb
Rails.application.routes.draw do
  mount EpicEditor::Engine => "/"
  
  resources :charges, only: [:new, :create]
  get 'charges/downgrade' => 'charges#downgrade' # Downgrade Accounts Path
  resources :wikis do
    resources :collaborators, only: [:index, :destroy, :create]
  end
  devise_for :users
  root 'wikis#index'

end

app/models/amount.rb
class Amount < ActiveRecord::Base
  def default
     15_00
  end
end

app/models/collaborator.rb
class Collaborator < ActiveRecord::Base
  belongs_to :user
  belongs_to :wiki
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable and :omniauthable
  # => Defaults a User to a standard account on creation
  before_save { self.role ||= :standard }
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,:confirmable

  enum role: [:standard, :premium, :admin]

  has_many :wikis
  has_many :collaborators
end

app/models/wiki.rb
class Wiki < ActiveRecord::Base
  belongs_to :user

  has_many :collaborators
  has_many :users, through: :collaborators

  def collaborator_for(user)
    collaborators.where(user_id: user.id).first
  end

  extend FriendlyId
  friendly_id :title, use: :slugged
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  include Pundit
  include Redcarpet
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  # before action callback for devise controller to utilize configure_permitted_parameters
  before_action :configure_permitted_parameters, if: :devise_controller?

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

protected

  def configure_permitted_parameters
    #devise_parameter_sanitizer.for is depreciated in Devise 4.2 so I switched to .permit
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:email, :password, :password_confirmation, :firstname, :lastname, :username) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:email, :password, :password_confirmation, :current_password, :firstname, :lastname, :username) }
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  @amount = 15_00

  def new
    @stripe_btn_data = {
      key: "#{ Rails.configuration.stripe[:publishable_key] }",
      description: "Blocpedia Premium Membership - #{current_user.username}",
      amount: @amount
     }
  end

  def create
    # The amount in pennies we will be charging the User
    @amount = 15_00

    # Creates a stripe Customer object to connect to the charge
    customer = Stripe::Customer.create(
      email: current_user.email,
      card: params[:stripeToken]
    )

    # Where the actual stripe charge is happening
    charge = Stripe::Charge.create(
      customer: customer.id, # not the user_id this is a stripe specific customer id number
      amount: @amount,
      description: "Blocpedia Premium Account for: #{current_user.username}",
      currency: 'usd'
    )

    # Upgrades the current_user to Premium
    current_user.premium!

    flash[:notice] = "Thanks for supporting Blocpedia, #{current_user.username}! Your account has been upgraded to Premium. If you have any questions please email admin@designxdevelop.com."
    # does't matter where we redirect this -- Use the User Path
    redirect_to wikis_path  #user_path(current_user)

  rescue Stripe::CardError => e
    flash[:alert] = e.message
    redirect_to new_charge_path
  end

  def downgrade
    current_user.standard!
    current_user.wikis.update_all(private: false)
    #current_user.wikis.private = false
    #@downgrade_wikis = Wiki.current_user.all
    # ^^^ I don't think these work because my charges controller won't have access to the Wiki's methods...
    redirect_to wikis_path # eventually redirect back to User Profile (TBAL)
    flash[:notice] = "Your account has been downgraded back to a Standard Account. All previously private wikis are now public."
  end
end

app/controllers/collaborators_controller.rb
class CollaboratorsController < ApplicationController
  before_action :set_wiki

  def index
    @users = User.all
  end

  def create
    @collaborator = @wiki.collaborators.new(user_id: params[:user_id])

    if @collaborator.save
      flash[:alert] = "Collaborator added Successfully to #{@wiki.title}"
    else
      flash[:notice] = "Oops... The collaborator could not be added. Please try again!"
    end

    redirect_to wiki_collaborators_path(@wiki)
  end

  def destroy
    @collaborator = Collaborator.find(params[:id])

    if @collaborator.destroy
      flash[:alert] = "Collaborator has been removed."
    else
      # flash oops
    end

    redirect_to wiki_collaborators_path(@wiki)

  end

  private

  def set_wiki
    @wiki = Wiki.friendly.find(params[:wiki_id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
  before_action :set_wiki, only: [:show, :edit, :update, :destroy]

  # GET /wikis
  def index
    @wikis = policy_scope(Wiki)
    #@wikis = policy_scope(Wiki.order(created_at: :desc)) #Orders Wiki's on Index View by Ascending Order or Newest First
  end

  # GET /wikis/1 or /wikis/slug
  def show
    authorize @wiki
    @wiki = Wiki.friendly.find(params[:id])
  end

  # GET /wikis/new
  def new
    @wiki = Wiki.new
    authorize @wiki
  end

  # GET /wikis/1/edit
  def edit
    authorize @wiki
  end

  # POST /wikis
  def create
    @wiki = current_user.wikis.new(wiki_params)
    authorize @wiki

    if @wiki.save
      redirect_to @wiki , notice: 'Wiki was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /wikis/1
  def update
    authorize @wiki
    if @wiki.update(wiki_params)
      @wiki.slug = nil #to update the slug it must be emptied and set to nil
      @wiki.save! # re-save the wiki so the new slug is generated
      redirect_to @wiki, notice: 'Wiki was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /wikis/1
  def destroy
    authorize @wiki
    @wiki.destroy
    redirect_to wikis_url, notice: 'Wiki was successfully deleted.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wiki
      @wiki = Wiki.friendly.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def wiki_params
      params.require(:wiki).permit(:title, :body, :private, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
# User Information Helpers
  def display_user_role
    # if current_user.role == 'standard'
    #   # span with standard class
    # else current_user.role == 'premium'
    #   # span with premium class
    # elsif current_user.role == 'admin'
    #   # span with admin class
    # end
    current_user.role.capitalize
  end

  def display_user_email
    current_user.email
  end

  def display_username
    current_user.username
  end

  def display_name
    current_user.firstname + " " + current_user.lastname
  end

  def display_collaborator_name(user)
    user.firstname + " " + user.lastname
  end

  def markdown(text)
    # sets options hash for Redcarpet markdown renderer
    options = { filter_html: true, hard_wrap: true, space_after_headers: true, fenced_code_blocks: true }
    # sets the extensions for the Redcarpet renderer
    extensions = { autolink: true, superscript: true, disable_indented_code_blocks: true }

    # sets up the renderer and calls the options hash for configuration of settings
    renderer = Redcarpet::Render::HTML.new(options)
    # extends the renderer abilities
    markdown = Redcarpet::Markdown.new(renderer, extensions)
    # renders the actual markdown styled text as .html_safe text
    markdown.render(text).html_safe
  end
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/collaborators_helper.rb
module CollaboratorsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wikis_helper.rb
module WikisHelper
end

app/views/charges/create.html.erb
<h1>Charges#create</h1>
<p>Find me in app/views/charges/create.html.erb</p>

app/views/charges/new.html.erb
<h1>Upgrade to Premium</h1>
<h4>All this for only $15!</h4>
<p>Premium Features</p>
<ul>
  <li>Private Wikis</li>
  <li>Support the Developer</li>
  <li>Access to Future Blocpedia Betas</li>
  <li>Personal Thank you from The Developer (In your profile after upgrade)</li>
</ul>
<p>Thank you for supporting me on my journey to become a web developer. --Austin</p>
<%= form_tag charges_path do %>
   <script class='stripe-button' src="https://checkout.stripe.com/checkout.js" data-key="<%= @stripe_btn_data[:key] %>" data-amount="<%= @stripe_btn_data[:amount] %>" data-description="<%= @stripe_btn_data[:description] %>" ></script>
 <% end %>

app/views/collaborators/index.html.erb
<h1>Manage Collaborators</h1>
<h3 class="wiki-title-collabs">Wiki: <em><%= @wiki.title %></em></h3>
<h3>Wiki Owner: <em><%= @wiki.user.email %></em></h3>

<table class="table table-striped">
  <thead>
    <th>User</th>
    <th></th>
  </thead>
  <% @users.each do |user| %>
    <tr>
      <td><%= user.email %></td>
      <td>
        <!-- check if user is a collaborator -->
        <% if @wiki.users.include?(user) %>
        <!-- if so, show remove button -->
          <% collaborator = @wiki.collaborator_for(user) %>
          <%= link_to "Remove as collaborator", [@wiki, collaborator], method: :delete, class: "btn btn-danger" %>
        <% else %>
        <!-- else show add button -->
          <%= link_to "Add as collaborator", wiki_collaborators_path(@wiki, user_id: user.id), method: :post, class: "btn btn-success" %>
        <% end %>
      </td>
    </tr>
  <% end %>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocpedia</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%# any embedded code with display_ is a HELPER in application_helper.rb  %>
  <nav class="navbar navbar-default">
    <div class="container"><%# using this to set a container in the nav bar %>
      <%= link_to   'Blocpedia',  root_path, :class => 'navbar-brand logo' %>
      <div class="pull-right">
        <% if user_signed_in? %>
          <div class="user-nav-links">
              Hello, <%= display_username %><br>
              <%= link_to 'Edit Profile', edit_user_registration_path, :class => 'navbar-link'%> | <%= link_to 'Sign Out', destroy_user_session_path, :method => :delete, :class => 'navbar-link' %>
          </div>
        <% else %>
          <div class="guest-nav-links">
            <%= link_to 'Sign Up', new_user_registration_path, :class => 'navbar-link' %> | <%= link_to 'Sign In', new_user_session_path, :class => 'navbar-link'  %>
          </div>
        <% end %>
      </div>
    </div>
  </nav>
  <div class="container">
    <div class="flash">
    <% if flash[:notice] %>
      <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:notice] %>
      </div>
    <% elsif flash[:error] %>
      <div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:error] %>
      </div>
    <% elsif flash[:warning] %>
      <div class=" alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:alert] %>
      </div>
    <% end %>
  </div>
<%= yield %>

  </div>
  <script type="text/javascript">
  $(document).ready(function(){
    // Tracks page views
    blocmetrics.report('Page Loads');
    // Tracks clicked links
    $('a').click(function(){
      blocmetrics.report('Links Clicked');
    });
  });
  </script>
</body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>

app/views/wikis/*_wikicontainer.html.erb
<% @wikis.each do |wiki| %>
  <div class="wiki-container" id="wiki-<%= wiki.id %>">
    <h1 class="wiki-title media media-heading">
      <%= link_to(wiki) do %>
      <%= wiki.title %>
      <% end %>
    </h1>
    <p class="wiki-body media">
      <%= link_to(wiki) do %>
      <%= wiki.body.truncate_words(70) %>
      <% end %>
    </p>

    <div class="wiki-status">
        <% if wiki.private? %>
          <span class="wiki-private">Private Wiki</span>
        <% else %>
          <span class="wiki-public">Public Wiki</span>
        <% end %>
      <div class="wiki-collaborator">
        <% if wiki.users.include?(current_user) %>
          <span class="wiki-collab">Collaborator</span>
        <% end %>
      </div>
    </div>

    <div class="wiki-info">
      <div class="wiki-published">
        Published: <%= time_ago_in_words(wiki.created_at) %> ago
      </div>
      <em>by</em>
      <div class="wiki-user">
         <%= wiki.user.email %>
      </div>
      <br>
      <div class="wiki-updated">
        Updated: <%= time_ago_in_words(wiki.updated_at) %> ago
      </div>
    </div>

    <div class="wiki-buttons">
      <div class="wiki-view">
        <%= link_to 'Read', wiki, class: 'btn btn-default' %>
      </div>
      <% if wiki.users.include?(current_user) || current_user.admin? || wiki.user == current_user %>
      <div class="wiki-edit">
        <%= link_to 'Edit', edit_wiki_path(wiki), class: 'btn btn-default' %>
      </div>
      <% end %>
      <% if wiki.user == current_user || current_user.admin? %>
      <div class="wiki-delete">
        <%= link_to 'Delete', wiki, class: 'btn btn-default', method: :delete, data: { confirm: 'Are you sure?' } %>
      </div>
      <% end %>

    </div>
  </div>
<% end  %>

app/views/wikis/_form.html.erb
<%= form_for(@wiki) do |f| %>
  <% if @wiki.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@wiki.errors.count, "error") %> prohibited this wiki from being saved:</h2>

      <ul>
      <% @wiki.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :body %><br>
    <%= f.text_area :body, class: 'form-control', rows: 10, columns: 20, style: "display:none;" %>
    <div id="epiceditor"></div>
  </div>

  <% if current_user.admin? || current_user.premium? %>
  <div class="form-group checkbox-fix">
    <%= f.label :private, class: 'checkbox' do %>
      <%= f.check_box :private %> Private wiki
    <% end %>
  </div>
<% end %>
<div class="inline-form-actions">
  <div class="actions">
    <%= f.submit class: 'btn btn-success' %>
  </div>
  <br>
</div>
<% end %>
<script type="text/javascript">
  var opts = {
  container: 'epiceditor',
  textarea: 'wiki_body',
  basePath: '/epiceditor',
  clientSideStorage: false,
  localStorageName: 'epiceditor',
  useNativeFullscreen: false,
  parser: marked,
  theme: {
    base: '/themes/base/epiceditor.css',
    preview: '/themes/preview/github.css',
    editor: '/themes/editor/epic-light.css'
  },
  button: {
    preview: true,
    fullscreen: true,
    bar: "auto"
  },
  focusOnLoad: false,
  shortcut: {
    modifier: 18,
    fullscreen: 70,
    preview: 80
  },
  string: {
    togglePreview: 'Toggle Preview Mode',
    toggleEdit: 'Toggle Edit Mode',
    toggleFullscreen: 'Enter Fullscreen'
  },
  autogrow: true
}
var editor = new EpicEditor(opts).load();
// var editor = new EpicEditor({basePath: '../../epiceditor'}).load();
</script>

app/views/wikis/_wiki.html.erb
<div class="wiki-container" id="wiki-<%= wiki.id %>">
  <h1 class="wiki-title media media-heading">
    <%= link_to(wiki) do %>
    <%= wiki.title %>
    <% end %>
  </h1>
  <p class="wiki-body media">
    <%= link_to(wiki) do %>
    <%= wiki.body.truncate_words(70) %>
    <% end %>
  </p>

  <div class="wiki-status">
      <% if wiki.private? %>
        <span class="wiki-private">Private Wiki</span>
      <% else %>
        <span class="wiki-public">Public Wiki</span>
      <% end %>
    <div class="wiki-collaborator">
      <% if wiki.users.include?(current_user) %>
        <span class="wiki-collab">Collaborator</span>
      <% end %>
    </div>
  </div>

  <div class="wiki-info">
    <div class="wiki-published">
      Published: <%= time_ago_in_words(wiki.created_at) %> ago
    </div>
    <em>by</em>
    <div class="wiki-user">
       <%= wiki.user.email %>
    </div>
    <br>
    <div class="wiki-updated">
      Updated: <%= time_ago_in_words(wiki.updated_at) %> ago
    </div>
  </div>

  <div class="wiki-buttons">
    <% if policy(wiki).show?  %>
      <div class="wiki-view">
        <%= link_to 'Read', wiki, class: 'btn btn-default btn-sm' %>
      </div>
    <% end %>
    <% if policy(wiki).edit? %>
      <div class="wiki-edit">
        <%= link_to 'Edit', edit_wiki_path(wiki), class: 'btn btn-default btn-sm' %>
      </div>
    <% end %>
    <% if policy(wiki).destroy?  %>
      <div class="wiki-delete">
        <%= link_to 'Delete', wiki, class: 'btn btn-default btn-sm', method: :delete, data: { confirm: 'Are you sure?' } %>
      </div>
    <% end %>
  </div>
</div>

app/views/wikis/_wikicontainer.html.erb
<% @wikis.each do |wiki| %>
  <div class="wiki-container" id="wiki-<%= wiki.id %>">
    <h1 class="wiki-title media media-heading">
      <%= link_to(wiki) do %>
      <%= wiki.title %>
      <% end %>
    </h1>
    <p class="wiki-body media">
      <%= link_to(wiki) do %>
      <%= wiki.body.truncate_words(70) %>
      <% end %>
    </p>

    <div class="wiki-status">
        <% if wiki.private? %>
          <span class="wiki-private">Private Wiki</span>
        <% else %>
          <span class="wiki-public">Public Wiki</span>
        <% end %>
      <div class="wiki-collaborator">
        <% if wiki.users.include?(current_user) %>
          <span class="wiki-collab">Collaborator</span>
        <% end %>
      </div>
    </div>

    <div class="wiki-info">
      <div class="wiki-published">
        Published: <%= time_ago_in_words(wiki.created_at) %> ago
      </div>
      <em>by</em>
      <div class="wiki-user">
         <%= wiki.user.email %>
      </div>
      <br>
      <div class="wiki-updated">
        Updated: <%= time_ago_in_words(wiki.updated_at) %> ago
      </div>
    </div>

    <div class="wiki-buttons">
      <div class="wiki-view">
        <%= link_to 'Read', wiki, class: 'btn btn-default' %>
      </div>
      <% if wiki.users.include?(current_user) || current_user.admin? || wiki.user == current_user %>
      <div class="wiki-edit">
        <%= link_to 'Edit', edit_wiki_path(wiki), class: 'btn btn-default' %>
      </div>
      <% end %>
      <% if wiki.user == current_user || current_user.admin? %>
      <div class="wiki-delete">
        <%= link_to 'Delete', wiki, class: 'btn btn-default', method: :delete, data: { confirm: 'Are you sure?' } %>
      </div>
      <% end %>

    </div>
  </div>
<% end  %>

app/views/wikis/edit.html.erb
<div class="page-heading">
  <h1>Editing Wiki</h1>
</div>

<%= render 'form' %><br>
<p>
  <em><strong>Wiki Editors:</strong></em> Please leave a line at the bottom of the wiki with " *your username* -- reason for edits " if you decide to save your edits.
</p>
<div class="collaborator-btn">
  <% if @wiki.user == current_user || current_user.admin? %>
    <%= link_to "Manage collaborators", wiki_collaborators_path(@wiki), class: "btn btn-info btn-md" %>
  <% end %>
</div>
<br>
<%= link_to 'Read', @wiki, class: 'btn btn-default btn-sm' %> |
<%= link_to 'Back', wikis_path, class: 'btn btn-default btn-sm' %>

app/views/wikis/index.html.erb
<div class="page-heading">
  <h1 class="media media-heading">All Wikis</h1>
</div>
<%= link_to 'New Wiki', new_wiki_path, class: 'btn btn-success' %>

<%# loops through all wikis and renders them out using the _wiki.html.erb as the formatting template for each wiki %>
<%= render @wikis %>

app/views/wikis/new.html.erb
<h1>New Wiki</h1>

<%= render 'form' %>
<br>
<%= link_to 'Back', wikis_path, class: 'btn btn-default btn-sm' %>

app/views/wikis/show.html.erb
<p class="title">
  <strong>Title:</strong>
  <%= @wiki.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= markdown(@wiki.body) %>
  <%# markdown method is configured in the application_helper.rb  %>
</p>

<p>
  <strong>Wiki Info:</strong>
  <div class="single-wiki-info">
    <% if @wiki.private? %>
      <span class="private">Private Wiki</span>
    <% else %>
      <span class="public">Public Wiki</span>
    <% end %>
    <br>
    <% if @wiki.users.include?(current_user) %>
      <span class="collaborator">Collaborator</span>
    <% end %>
  </div>
</p>

<p>
  <strong>Author:</strong>
  <%= @wiki.user.email %>
</p>
<%= link_to 'Back', wikis_path, class: 'btn btn-default btn-sm' %>
<% if policy(@wiki).edit? %>
| <%= link_to 'Edit', edit_wiki_path(@wiki), class: 'btn btn-default btn-sm' %>
<% end %>
<% if policy(@wiki).destroy? %>
| <%= link_to 'Delete', @wiki, class: 'btn btn-default btn-sm', method: :delete, data: { confirm: 'Are you sure?' } %>
<% end %>